# Generated by Django 5.2.3 on 2025-07-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_comments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
